# Generated by Django 3.1.6 on 2021-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_and_pay', '0002_auto_20210301_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('order_is_made', 'Заказ оформлен'), ('order_is_paid', 'Заказ оплачен'), ('order_is_fulfilled', 'Заказ выполнен')], default='Saint-Petersburg', max_length=200, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('spb', 'Санкт-Петербург'), ('psh', 'Пушкин'), ('gatchina', 'Гатчина'), ('vsecologsk', 'Всеволожск')], default='Saint-Petersburg', max_length=200, verbose_name='Город'),
        ),
    ]
