# Generated by Django 3.2 on 2021-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_and_pay', '0006_auto_20210417_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
