# Generated by Django 3.2 on 2021-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_and_pay', '0008_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('sb', 'Сосновый бор')], default='Saint-Petersburg', max_length=200, verbose_name='Город'),
        ),
    ]
