# Generated by Django 3.1.6 on 2021-02-18 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210208_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slag',
            field=models.SlugField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
