# Generated by Django 3.1.6 on 2021-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slag',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Слаг'),
        ),
    ]
