# Generated by Django 3.2 on 2021-05-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_globalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='global_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.globalcategory', verbose_name='Глобальная категория'),
            preserve_default=False,
        ),
    ]
