# Generated by Django 3.2 on 2021-05-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_global_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_pack',
        ),
    ]
