# Generated by Django 3.2 on 2021-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('piece', 'шт.'), ('kilogram', 'кг.'), ('gram', 'гр.'), ('centimeter', 'см.'), ('meter', 'м.')], default='piece', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
