# Generated by Django 3.2 on 2021-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('piece', 'штуку'), ('kilogram', 'килограмм'), ('gram', 'грамм'), ('centimeter', 'сантиметр'), ('meter', 'метр')], default='piece', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
