# Generated by Django 3.2 on 2021-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_unit_of_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Подробное пожелание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('wish_is_made', 'Создано'), ('wish_is_done', 'Выполнено'), ('wish_is_fulfilled', 'Отклонено')], default='wish_is_made', max_length=200, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пожелание',
                'verbose_name_plural': 'Пожелания',
                'ordering': ['-created_at'],
            },
        ),
    ]
