# Generated by Django 3.2 on 2021-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_title', models.CharField(max_length=150, verbose_name='Ключ')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('value', models.CharField(max_length=1000, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
