# Generated by Django 3.2 on 2021-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210604_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
    ]
