# Generated by Django 3.2 on 2021-06-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_sitesettings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='contacts',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адрес электронной почты либо телефон'),
        ),
    ]
