# Generated by Django 3.2 on 2021-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_wish_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
