# Generated by Django 3.2 on 2021-10-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_sitesettings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='global_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category_photos/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='GlobalCategory',
        ),
    ]
