# Generated by Django 3.1.6 on 2021-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
